[project]
name = "update-key-bindings"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "Andreas Xue", email = "39456468+ilearnings@users.noreply.github.com" },
]
requires-python = ">=3.13"
dependencies = ["pyyaml>=6.0.3"]

[dependency-groups]
dev = ["types-pyyaml>=6.0.12.20260906"]
