draw_config:
  key_w: 108
  key_h: 100.8
  append_colon_to_layer_header: false
  key_font: "Microsoft YaHei, Noto Sans CJK SC, sans-serif"
  key_font_size: 8
  shrink_wide_legends: 5
  line_spacing: 1.3
  svg_extra_style: |
    .key .legend {
      font-weight: bold;
    }
    rect.key.bound {
      fill: #87CEEB;
    }
    rect.key.mouse {
      fill: #FFE4A0;
    }
